### ISSUE TITLE
stack trace from debian/jessie + rethinkdb

### ISSUE THREAD

**Issue by schvin** [cglewis/bowl#1]
Ran through build, picked Jessie & rethinkdb, built w/ container not found error.

```
The following services have been selected and will be packaged up into a container:
[u'debian:jessie:databases:rethinkdb, default']

### GENERATED DOCKERFILE ###
# http://www.rethinkdb.com/
# version 1.13.3
FROM debian:jessie

RUN echo "deb http://download.rethinkdb.com/apt lucid main" | tee /etc/apt/sources.list.d/rethinkdb.list
ADD rethinkdb/http://download.rethinkdb.com/apt/pubkey.gpg /pubkey.gpg
RUN apt-key add pubkey.gpg && apt-get update && \
    apt-get install -y rethinkdb && \
    mkdir /rethinkdb && chown -R daemon:daemon /rethinkdb
# process cluster webui
EXPOSE 28015 29015 8080
WORKDIR /rethinkdb
ENTRYPOINT ["/usr/bin/rethinkdb"]
CMD ["--bind", "all"]
### END GENERATED DOCKERFILE ###

['{"stream":" ---\\u003e badcb042f7c9\\n"}\r\n', '{"stream":"Step 1 : RUN echo \\"deb http://download.rethinkdb.com/apt lucid main\\" | tee /etc/apt/sources.list.d/rethinkdb.list\\n"}\r\n', '{"stream":" ---\\u003e Using cache\\n"}\r\n', '{"stream":" ---\\u003e edf05a69f7c5\\n"}\r\n', '{"stream":"Step 2 : ADD rethinkdb/http://download.rethinkdb.com/apt/pubkey.gpg /pubkey.gpg\\n"}\r\n', '{"errorDetail":{"message":"rethinkdb/http://download.rethinkdb.com/apt/pubkey.gpg: no such file or directory"},"error":"rethinkdb/http://download.rethinkdb.com/apt/pubkey.gpg: no such file or directory"}\r\n']
Traceback (most recent call last):
  File "/usr/local/bin/bowl", line 9, in <module>
    load_entry_point('bowl==0.3.0', 'console_scripts', 'bowl')()
  File "/usr/local/lib/python2.7/dist-packages/bowl/cli.py", line 428, in main
    cli().parse_args()
  File "/usr/local/lib/python2.7/dist-packages/bowl/cli.py", line 425, in parse_args
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/bowl/cli_opts/new.py", line 933, in main
    self.build_dockerfile(self, dockerfile, uuid_dir, args)
  File "/usr/local/lib/python2.7/dist-packages/bowl/cli_opts/new.py", line 130, in build_dockerfile
    hostname=image_tag)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 514, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 522, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 92, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 88, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("No such image: bowl-17c1cf78-28ae-40a1-a5da-0189678d4324 (tag: latest)")
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                   NAMES
877d4ac81063        schvin/newsbeuter:latest   "/usr/bin/newsbeuter   6 days ago          Up 6 days                                   sad_wozniak
ef1a31b2a40d        wharf-stable:latest        "python api.py"        3 months ago        Up 5 days           0.0.0.0:80->26002/tcp   mad_sinoussi
$ docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
$
```

**Comment by schvin** [comment]
as you suspected, alternate configurations worked w/o issue (did ubuntu 14.04 + golang).

**Comment by cglewis** [comment]
thanks for discovering this issue, should be resolved now!
